# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca5caca4d1cd79bab01c7c817d204811afaffcffc2d5aec44d6e2602cbe0b1be8ec18abf7abd165aa0e733ba96bf74958d9444e7fdce218842a2e4e5216b5164

test:
  secret_key_base: 18aa97e3a043433cd95f0f3f30c41d9f0cf6ee6c4e602b95f386e97e5e377fbad6379f8f74350424c460a0a71f62c44d11c9f67b85a4e63be2019a99fdb2ae7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
